In [2]:
import numpy as np

X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])

y = np.array([[0,1,1,0]]).T

In [15]:
alpha, hidden_dim, d_p, do_d = (0.5, 4, 20.0/100, True)

In [16]:
%whos

Variable     Type       Data/Info
---------------------------------
X            ndarray    4x3: 12 elems, type `int64`, 96 bytes
alpha        float      0.5
d_p          float      0.2
do_d         bool       True
hidden_dim   int        4
np           module     <module 'numpy' from '/ho<...>ages/numpy/__init__.pyc'>
y            ndarray    4x1: 4 elems, type `int64`, 32 bytes


In [17]:
syn0 = 2*np.random.random((3,hidden_dim)) - 1
syn1 = 2*np.random.random((hidden_dim,1)) - 1

In [18]:
def sig(x):
    return(1/(1+np.exp(-x)))

def sig_d(o):
    return(o*(1-o))

In [27]:
for iter in xrange(700000):
    
    #Fwd
    l1 = sig(np.dot(X, syn0))
    
    if(do_d):
        l1 = l1 * np.random.binomial(
            
            [np.ones((len(X), hidden_dim))],
            1 - d_p)[0] * (1.0/(1-d_p))
        
        
    l2 = sig(np.dot(l1, syn1))
    
    #Back
    
    l2_del = (l2 - y) * sig_d(l2)
    l1_del = np.dot(l2_del, syn1.T) * sig_d(l1)
    
    syn1 -= (alpha * np.dot(l1.T, l2_del))
    syn0 -= (alpha * np.dot(X.T,  l1_del))
    
    if iter%100000==0:
        print(l2)
        print("*****")

[[ 0.00663703]
 [ 0.91540997]
 [ 0.76450266]
 [ 0.00920367]]
*****
[[ 0.00398023]
 [ 0.91824229]
 [ 0.79022298]
 [ 0.00607958]]
*****
[[ 0.00440819]
 [ 0.90224984]
 [ 0.90288682]
 [ 0.0013873 ]]
*****
[[ 0.001754  ]
 [ 0.79519903]
 [ 0.88714207]
 [ 0.00426214]]
*****
[[  2.37054742e-03]
 [  9.39925496e-01]
 [  7.46547999e-01]
 [  9.11940419e-04]]
*****
[[  7.33508580e-01]
 [  7.22290440e-01]
 [  9.00753955e-01]
 [  8.48369903e-04]]
*****


/home/rahul/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:2: RuntimeWarning: overflow encountered in exp
  from ipykernel import kernelapp as app


[[ 0.00088511]
 [ 0.88099169]
 [ 0.59630636]
 [ 0.00393995]]
*****


KeyboardInterrupt: 

In [26]:
import numpy as np
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
alpha,hidden_dim,dropout_percent,do_dropout = (0.5,4,0.2,True)
synapse_0 = 2*np.random.random((3,hidden_dim)) - 1
synapse_1 = 2*np.random.random((hidden_dim,1)) - 1
for j in xrange(70000):
    layer_1 = (1/(1+np.exp(-(np.dot(X,synapse_0)))))
    if(do_dropout):
        layer_1 *= np.random.binomial([np.ones((len(X),hidden_dim))],1-dropout_percent)[0] * (1.0/(1-dropout_percent))
    layer_2 = 1/(1+np.exp(-(np.dot(layer_1,synapse_1))))
    layer_2_delta = (layer_2 - y)*(layer_2*(1-layer_2))
    layer_1_delta = layer_2_delta.dot(synapse_1.T) * (layer_1 * (1-layer_1))
    synapse_1 -= (alpha * layer_1.T.dot(layer_2_delta))
    synapse_0 -= (alpha * X.T.dot(layer_1_delta))
    if j%10000==0: print(layer_2)

[[ 0.41963183]
 [ 0.38779427]
 [ 0.32905122]
 [ 0.35736131]]
[[ 0.12239089]
 [ 0.95771924]
 [ 0.99638866]
 [ 0.10038675]]
[[ 0.03739227]
 [ 0.41393245]
 [ 0.92915471]
 [ 0.52164696]]
[[ 0.05320669]
 [ 0.93871094]
 [ 0.99616886]
 [ 0.05562511]]
[[ 0.00312003]
 [ 0.4930627 ]
 [ 0.92112547]
 [ 0.00306919]]
[[ 0.04748418]
 [ 0.9314812 ]
 [ 0.95255075]
 [ 0.06046726]]
[[ 0.12329674]
 [ 0.56695406]
 [ 0.97386857]
 [ 0.0662658 ]]
