In [2]:
import numpy as np

In [3]:
#Nonlinearity, here sigmoid func and derivative
#Could be someother function as well

def nonlin(x, deriv=False):
    if(deriv==True):
        return(x*(1-x))
    else:
        return( 1/(1 + np.exp(-x)) )

In [4]:
#Tests
nonlin(0)#x=0, nonlin(0.5, deriv=True)#Here x=0, sigmoid=0.5

0.5

In [5]:
#Input dataset

X = np.array([
                [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1],
])

In [6]:
X[1] , X[1][1]

(array([0, 1, 1]), 1)

In [7]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [8]:
#Output Dataset
y = np.array([[0,0,1,1]]).T

In [9]:
y

array([[0],
       [0],
       [1],
       [1]])

In [10]:
y[0]

array([0])

In [11]:
np.random.seed(1)

In [18]:
#Populate 1st layer with random weights
#We need to shift spread (0 to 1) to (-1 to 1)
syn0 = 2*np.random.random((3,1)) - 1
syn0

array([[-0.62747958],
       [-0.30887855],
       [-0.20646505]])

In [19]:
for iter in xrange(10000):
    
    #Fwd prop
    l0 = X #Input layer
    l1 = nonlin(np.dot(l0,syn0)) #L1 gives predictions
    #if (iter == 1) or (iter%1000 == 0):
    #    print(l1)
    #    print("****************")
    
    #Find error between expected and predicted 
    l1_error = y - l1
    if (iter == 1) or (iter%1000 == 0):
        print(l1_error)
        print("****************")
    
    #What fraction of input to move towards 
    l1_delta = l1_error * nonlin(l1, deriv = True)
    
    #Move weights towards product of inputs and faction movement
    syn0 = syn0 + np.dot(l0.T, l1_delta)
    
    
print("Output after Training:")
print(l1) 

[[-0.44856632]
 [-0.3739417 ]
 [ 0.69718835]
 [ 0.7581976 ]]
****************
[[-0.47034194]
 [-0.40704614]
 [ 0.61302834]
 [ 0.67205143]]
****************
[[-0.03195016]
 [-0.02573781]
 [ 0.02088504]
 [ 0.02595728]]
****************
[[-0.02216442]
 [-0.01792967]
 [ 0.01457753]
 [ 0.01803509]]
****************
[[-0.01794692]
 [-0.01454433]
 [ 0.01183495]
 [ 0.01461309]]
****************
[[-0.01546616]
 [-0.01254728]
 [ 0.01021487]
 [ 0.01259809]]
****************
[[-0.01378727]
 [-0.01119329]
 [ 0.00911555]
 [ 0.0112335 ]]
****************
[[-0.0125552 ]
 [-0.01019839]
 [ 0.00830731]
 [ 0.01023162]]
****************
[[-0.01160183]
 [-0.00942781]
 [ 0.00768104]
 [ 0.0094561 ]]
****************
[[-0.010836  ]
 [-0.00880835]
 [ 0.00717741]
 [ 0.00883296]]
****************
[[-0.01020343]
 [-0.00829637]
 [ 0.00676105]
 [ 0.00831814]]
****************
Output after Training:
[[ 0.00967004]
 [ 0.00786445]
 [ 0.99359029]
 [ 0.99211604]]


In [43]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv == True:
        return(x*(1-x))
    else:
        return(1/(1+np.exp(-x)))
    
    
X = np.array([
        
        [0,0,1],
        [0,1,1],
        [1,0,1],
        [1,1,1]
    ])

y = np.array([
        
        [0],
        [1],
        [1],
        [0] 
    ])

np.random.seed(1)


#Init the 2 layer weights
#     o
# o   o
# o   o    o
# o   o
# I   H    O
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1


for j in xrange(6000):
    
    #Fwd pass activations
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    #Error, start from last layer
    
    l2_error = y - l2
    l2_delta = l2_error*nonlin(l2,deriv=True)
    
    
    l1_error =  l2_delta.dot(syn1.T)
    l1_delta =  l1_error*nonlin(l1,deriv=True)
    
    syn1 = syn1 + np.dot(l1.T,l2_delta)
    syn0 = syn0 + np.dot(l0.T,l1_delta)
    
    if (j% 10000) == 0:
        print "Error:" + str(np.mean(np.abs(l2_error)))
    
print(l2_error) 
    
    


Error:0.496410031903
[[-0.00953041]
 [ 0.01222792]
 [ 0.01055641]
 [-0.01422542]]


In [40]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv == True:
        return(x*(1-x))
    else:
        return(1/(1+np.exp(-x)))
    
    
X = np.array([
        
        [0,0,1],
        [0,1,1],
        [1,0,1],
        [1,1,1]
    ])

y = np.array([
        
        [0],
        [1],
        [1],
        [0] 
    ])

np.random.seed(1)


#Init the 2 layer weights
#     o
# o   o
# o   o    o
# o   o
# I   H    O
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for j in xrange(60000):

	# Feed forward through layers 0, 1, and 2
    
        #Fwd pass activations
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    #Error, start from last layer
    
    l2_error = y - l2
    l2_delta = l2_error*nonlin(l2,deriv=True)
    
    
    l1_error =  l2_delta.dot(syn1.T)
    l1_delta =  l1_error*nonlin(l1,deriv=True)
    
    syn1 = syn1 + l1.T.dot(l2_delta)
    syn0 = syn0 + l0.T.dot(l1_delta)
    
    
    if (j% 10000) == 0:
        print "Error:" + str(np.mean(np.abs(l2_error)))
        



Error:0.496410031903
Error:0.00858452565325
Error:0.00578945986251
Error:0.00462917677677
Error:0.00395876528027
Error:0.00351012256786
