In [3]:
import numpy as np

X = np.array([
        
        [0,0,1],
        [0,1,1],
        [1,0,1],
        [1,1,1]
    ])

y = np.array([
        
        [0,1,1,0]
    ]).T

alpha = 0.5

num_eg = X.shape[0]

num_in = X.shape[1]
hidden_dim = 4
num_out = y.shape[1]

syn0 = 2*np.random.random((num_in, hidden_dim))  - 1
syn1 = 2*np.random.random((hidden_dim, num_out)) - 1


%whos

Variable     Type       Data/Info
---------------------------------
X            ndarray    4x3: 12 elems, type `int64`, 96 bytes
alpha        float      0.5
hidden_dim   int        4
np           module     <module 'numpy' from '/ho<...>ages/numpy/__init__.pyc'>
num_eg       int        4
num_in       int        3
num_out      int        1
syn0         ndarray    3x4: 12 elems, type `float64`, 96 bytes
syn1         ndarray    4x1: 4 elems, type `float64`, 32 bytes
y            ndarray    4x1: 4 elems, type `int64`, 32 bytes


In [4]:
def nonlin(x):
    return(1/(1+np.exp(-x)))

def nonlin_deriv(y):
    return(y*(1-y))


In [5]:
for iter in xrange(70000):
    #Forward pass
    l1 = nonlin(np.dot( X,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    
    #Backward
    l2_err = (l2 - y)
    l2_del = l2_err * nonlin_deriv(l2)
    l1_err = np.dot(l2_del, syn1.T)
    l1_del = l1_err * nonlin_deriv(l1)
    
    #Update weights
    
    syn1 = syn1 - alpha*(np.dot(l1.T, l2_del))
    syn0 = syn0 - alpha*(np.dot(X.T,  l1_del))
    
    if iter%10000==0:
        print(l2)
        print("******")
    

[[ 0.55710764]
 [ 0.56367712]
 [ 0.57777212]
 [ 0.59368262]]
******
[[ 0.01601755]
 [ 0.98322461]
 [ 0.98269445]
 [ 0.02141446]]
******
[[ 0.01078585]
 [ 0.98883095]
 [ 0.98843976]
 [ 0.01419602]]
******
[[ 0.00863903]
 [ 0.991094  ]
 [ 0.99076242]
 [ 0.01131052]]
******
[[ 0.00740042]
 [ 0.99239111]
 [ 0.99209516]
 [ 0.00966225]]
******
[[ 0.00657119]
 [ 0.99325617]
 [ 0.99298478]
 [ 0.00856486]]
******
[[ 0.00596695]
 [ 0.99388488]
 [ 0.99363183]
 [ 0.00776808]]
******


In [6]:
import numpy as np

def sigmoid(x):
    return(1/(1+np.exp(-x)))

def sigmoid_o_to_deriv(output):
    return(output*(1-output))


X = np.array([
        
        [0,1],
        [0,1],
        [1,0],
        [1,0]
    ])

y = np.array([[0,0,1,1]]).T


np.random.seed(1)

syn0 = 2*np.random.random((2,1)) - 1

for iter in xrange(70000):
    
    #Fwd
    l0 = X
    l1 = sigmoid(np.dot(l0,syn0))
    
    #Back
    l1_err = l1 - y
    l1_del = l1_err * (sigmoid_o_to_deriv(l1))
    
    syn0_deriv = np.dot(l0.T,l1_del)
    
    syn0 = syn0 - syn0_deriv
    
    if iter%10000==0:
        print(l1)
        print("*****")
    



[[ 0.60841366]
 [ 0.60841366]
 [ 0.45860596]
 [ 0.45860596]]
*****
[[ 0.00505094]
 [ 0.00505094]
 [ 0.99494931]
 [ 0.99494931]]
*****
[[ 0.00356088]
 [ 0.00356088]
 [ 0.99643921]
 [ 0.99643921]]
*****
[[ 0.00290361]
 [ 0.00290361]
 [ 0.99709644]
 [ 0.99709644]]
*****
[[ 0.00251263]
 [ 0.00251263]
 [ 0.9974874 ]
 [ 0.9974874 ]]
*****
[[ 0.00224616]
 [ 0.00224616]
 [ 0.99775386]
 [ 0.99775386]]
*****
[[ 0.00204965]
 [ 0.00204965]
 [ 0.99795037]
 [ 0.99795037]]
*****


In [7]:
import numpy as np
alphas = [10**x for x in range(-3,4)] #10^-3 to 10^3

In [8]:
def sig(x):
    return(1/(1+np.exp(-x)))

def sig_o_to_d(y):
    return(y*(1-y))

In [9]:
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
			[1],
			[1],
			[0]])


In [10]:
%whos

Variable     Type        Data/Info
----------------------------------
X            ndarray     4x3: 12 elems, type `int64`, 96 bytes
alpha        int         100
alphas       list        n=7
iter         int         69999
l0           ndarray     4x3: 12 elems, type `int64`, 96 bytes
l1           ndarray     4x10: 40 elems, type `float64`, 320 bytes
l1_del       ndarray     4x10: 40 elems, type `float64`, 320 bytes
l1_err       ndarray     4x10: 40 elems, type `float64`, 320 bytes
l2           ndarray     4x1: 4 elems, type `float64`, 32 bytes
l2_del       ndarray     4x1: 4 elems, type `float64`, 32 bytes
l2_err       ndarray     4x1: 4 elems, type `float64`, 32 bytes
np           module      <module 'numpy' from '/ho<...>ages/numpy/__init__.pyc'>
sig          function    <function sig at 0x7f474c089aa0>
sig_o_to_d   function    <function sig_o_to_d at 0x7f474c089398>
syn0         ndarray     3x10: 30 elems, type `float64`, 240 bytes
syn1         ndarray     10x1: 10 elems, type `floa

In [11]:
np.random.seed(1)

for alpha in alphas:
    print("\nTraining with alpha =" + str(alpha))
    
    syn0 = 2*np.random.random((3,10)) - 1
    syn1 = 2*np.random.random((10,1)) - 1
    
    
    for iter in xrange(70000):
        
        #Fwd
        l0 = X
        l1 = sig(np.dot(l0,syn0))
        l2 = sig(np.dot(l1,syn1))
        
        #Back
        l2_err = l2 - y
        l2_del = l2_err * sig_o_to_d(l2)
        
        l1_err = np.dot(l2_del, syn1.T)
        l1_del = l1_err * sig_o_to_d(l1)
        
        syn1 = syn1 - alpha*(np.dot(l1.T, l2_del))
        syn0 = syn0 - alpha*(np.dot(l0.T, l1_del))
        
        
        if (iter% 10000) == 0:
            print("Error after "+str(iter)+" iterations:" + str(np.mean(np.abs(l2_err))) )
    
    


Training with alpha =0.001
Error after 0 iterations:0.502439933352
Error after 10000 iterations:0.50066317614
Error after 20000 iterations:0.499114061042
Error after 30000 iterations:0.497584851854
Error after 40000 iterations:0.49592699499
Error after 50000 iterations:0.494004810615
Error after 60000 iterations:0.491678246364

Training with alpha =0.01
Error after 0 iterations:0.495585561818
Error after 10000 iterations:0.448288116418
Error after 20000 iterations:0.24422254869
Error after 30000 iterations:0.123588778674
Error after 40000 iterations:0.0849371487792
Error after 50000 iterations:0.0668996869526
Error after 60000 iterations:0.0563365660254

Training with alpha =0.1
Error after 0 iterations:0.502063469966
Error after 10000 iterations:0.0358940190793
Error after 20000 iterations:0.0217119164645
Error after 30000 iterations:0.0167163432351
Error after 40000 iterations:0.0140070203506
Error after 50000 iterations:0.0122569168161
Error after 60000 iterations:0.0110119492882



In [12]:
import numpy as np

alphas = [0.001,0.01,0.1,1,10,100,1000]

# compute sigmoid nonlinearity
def sigmoid(x):
    output = 1/(1+np.exp(-x))
    return output

# convert output of sigmoid function to its derivative
def sigmoid_output_to_derivative(output):
    return output*(1-output)
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
			[1],
			[1],
			[0]])



for alpha in alphas:
    print "\nTraining With Alpha:" + str(alpha)
    np.random.seed(1)

    # randomly initialize our weights with mean 0
    synapse_0 = 2*np.random.random((3,4)) - 1
    synapse_1 = 2*np.random.random((4,1)) - 1
        
    prev_synapse_0_weight_update = np.zeros_like(synapse_0)
    prev_synapse_1_weight_update = np.zeros_like(synapse_1)

    synapse_0_direction_count = np.zeros_like(synapse_0)
    synapse_1_direction_count = np.zeros_like(synapse_1)
        
    for j in xrange(60000):

        # Feed forward through layers 0, 1, and 2
        layer_0 = X
        layer_1 = sigmoid(np.dot(layer_0,synapse_0))
        layer_2 = sigmoid(np.dot(layer_1,synapse_1))

        # how much did we miss the target value?
        layer_2_error = y - layer_2

        if (j% 10000) == 0:
            print "Error:" + str(np.mean(np.abs(layer_2_error)))

        # in what direction is the target value?
        # were we really sure? if so, don't change too much.
        layer_2_delta = layer_2_error*sigmoid_output_to_derivative(layer_2)

        # how much did each l1 value contribute to the l2 error (according to the weights)?
        layer_1_error = layer_2_delta.dot(synapse_1.T)

        # in what direction is the target l1?
        # were we really sure? if so, don't change too much.
        layer_1_delta = layer_1_error * sigmoid_output_to_derivative(layer_1)
        
        synapse_1_weight_update = (layer_1.T.dot(layer_2_delta))
        synapse_0_weight_update = (layer_0.T.dot(layer_1_delta))
        
        if(j > 0):
            synapse_0_direction_count += np.abs(((synapse_0_weight_update > 0)+0) - ((prev_synapse_0_weight_update > 0) + 0))
            synapse_1_direction_count += np.abs(((synapse_1_weight_update > 0)+0) - ((prev_synapse_1_weight_update > 0) + 0))        
        
        synapse_1 += alpha * synapse_1_weight_update
        synapse_0 += alpha * synapse_0_weight_update
        
        prev_synapse_0_weight_update = synapse_0_weight_update
        prev_synapse_1_weight_update = synapse_1_weight_update
    
    print "Synapse 0"
    print synapse_0
    
    print "Synapse 0 Update Direction Changes"
    print synapse_0_direction_count
    
    print "Synapse 1"
    print synapse_1

    print "Synapse 1 Update Direction Changes"
    print synapse_1_direction_count


Training With Alpha:0.001
Error:0.496410031903
Error:0.495164025493
Error:0.493596043188
Error:0.491606358559
Error:0.489100166544
Error:0.485977857846
Synapse 0
[[-0.28448441  0.32471214 -1.53496167 -0.47594822]
 [-0.7550616  -1.04593014 -1.45446052 -0.32606771]
 [-0.2594825  -0.13487028 -0.29722666  0.40028038]]
Synapse 0 Update Direction Changes
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 1.  0.  1.  1.]]
Synapse 1
[[-0.61957526]
 [ 0.76414675]
 [-1.49797046]
 [ 0.40734574]]
Synapse 1 Update Direction Changes
[[ 1.]
 [ 1.]
 [ 0.]
 [ 1.]]

Training With Alpha:0.01
Error:0.496410031903
Error:0.457431074442
Error:0.359097202563
Error:0.239358137159
Error:0.143070659013
Error:0.0985964298089
Synapse 0
[[ 2.39225985  2.56885428 -5.38289334 -3.29231397]
 [-0.35379718 -4.6509363  -5.67005693 -1.74287864]
 [-0.15431323 -1.17147894  1.97979367  3.44633281]]
Synapse 0 Update Direction Changes
[[ 1.  1.  0.  0.]
 [ 2.  0.  0.  2.]
 [ 4.  2.  1.  1.]]
Synapse 1
[[-3.70045078]
 [ 4.57578637]
 [-7.