In [1]:
import numpy as np

In [2]:
#Nonlinearity, here sigmoid func and derivative
#Could be someother function as well

def nonlin(x, deriv=False):
    if(deriv==True):
        return(x*(1-x))
    else:
        return( 1/(1 + np.exp(-x)) )

In [5]:
#Tests
nonlin(0)#x=0, nonlin(0.5, deriv=True)#Here x=0, sigmoid=0.5

(0.5, 0.25)

In [6]:
#Input dataset

X = np.array([
                [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1],
])

In [8]:
X[1] , X[1][1]

(array([0, 1, 1]), 1)

In [11]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [9]:
#Output Dataset
y = np.array([[0,0,1,1]]).T

In [10]:
y

array([[0],
       [0],
       [1],
       [1]])

In [17]:
y[0]

array([0])

In [18]:
np.random.seed(1)

In [33]:
#Populate 1st layer with random weights
#We need to shift spread (0 to 1) to (-1 to 1)
syn0 = 2*np.random.random((3,1)) - 1
syn0

array([[-0.9444333 ],
       [ 0.50972296],
       [-0.21029904]])

In [45]:
for iter in xrange(10000):
    
    #Fwd prop
    l0 = X #Input layer
    l1 = nonlin(np.dot(l0,syn0)) #L1 gives predictions
    
    #Find error between expected and predicted 
    l1_error = y - l1
    
    #What fraction of input to move towards 
    l1_delta = l1_error * nonlin(l1, deriv = True)
    
    #Move weights towards product of inputs and faction movement
    syn0 = syn0 + np.dot(l0.T, l1_delta)
    
    
print("Output after Training:")
print(l1) 

Output after Training:
[[ 0.00231059]
 [ 0.00188493]
 [ 0.9984616 ]
 [ 0.99811405]]
