In [1]:
class VerySimpleStack:
    
    def __init__(self):
        self.contents = list()
        
    def push(self,item):
        self.contents.append(item)
    
    def pop(self):
        item = self.contents[-1]
        self.contents = self.contents[:-1]
        return item
    
    def pretty_print(self):
      i = 1
      print "\n--------TOP---------"
      for item in (self.contents):
          if(i != 1):
              print "--------------------"            
          print self.contents[-i]
          i+=1

      print  "-----------------------"
      print  "---------(table)-------"
      print  "-----------------------"
      print  "-- --             -- --"            
      print  "-- --             -- --"            
      print  "-- --             -- --"            
      print  "-- --             -- --"            
      print  "--                --"            
      print  "--                --\n\n"            
      
        

print "1) Creating an empty stack of books..."
stack = VerySimpleStack()

print "2) Pushing two books onto our stack..."
stack.push("Harry Potter and the Sorcerer's Stone")
stack.push("Harry Potter and the Chamber of Secrets")

print "3) Let's look at our stack..."
stack.pretty_print() # what order will this print?

print "4)Let's Pop a few...\n"
print "POP: " + stack.pop() # which one does this remove?
print "POP: " + stack.pop() # how bout this one?

print "\n5)Let's push a few more!"

stack.push("Harry Potter and the Prisoner of Azkaban")
stack.push("Harry Potter and the Goblet of Fire")
stack.push("Harry Potter and the Order of the Phoenix")
stack.push("Harry Potter and the Half-Blood Prince")
stack.push("Harry Potter and the Deathly Hallows")


print "\n6)Let's look at our stack again..."
stack.pretty_print()




1) Creating an empty stack of books...
2) Pushing two books onto our stack...
3) Let's look at our stack...

--------TOP---------
Harry Potter and the Chamber of Secrets
--------------------
Harry Potter and the Sorcerer's Stone
-----------------------
---------(table)-------
-----------------------
-- --             -- --
-- --             -- --
-- --             -- --
-- --             -- --
--                --
--                --


4)Let's Pop a few...

POP: Harry Potter and the Chamber of Secrets
POP: Harry Potter and the Sorcerer's Stone

5)Let's push a few more!

6)Let's look at our stack again...

--------TOP---------
Harry Potter and the Deathly Hallows
--------------------
Harry Potter and the Half-Blood Prince
--------------------
Harry Potter and the Order of the Phoenix
--------------------
Harry Potter and the Goblet of Fire
--------------------
Harry Potter and the Prisoner of Azkaban
-----------------------
---------(table)-------
-----------------------
-- --         

In [2]:
class VerySimpleStack:
    
    def __init__(self):
        self.contents = list()
        
    def push(self,item):
        self.contents.append(item)
    
    def pop(self):
        item = self.contents[-1]
        self.contents = self.contents[:-1]
        return item
    
    def pretty_print(self):
      i = 1
      print "\n--------TOP---------"
      for item in (self.contents):
          if(i != 1):
              print "--------------------"            
          print self.contents[-i]
          i+=1

      print  "-----------------------"
      print  "---------(table)-------"
      print  "-----------------------"
      print  "-- --             -- --"            
      print  "-- --             -- --"            
      print  "-- --             -- --"            
      print  "-- --             -- --"            
      print  "--                --"            
      print  "--                --\n\n"            
      
        

print "1) Creating an empty stack of numbers..."
stack = VerySimpleStack()

print "\n2) Create an ordered sequence... "
sequence = [0,1,2,3,4,5]
print "sequence = " + str(sequence)

print "\n3) Push sequence onto my stack"
stack.push(sequence[0])
stack.push(sequence[1])
stack.push(sequence[2])
stack.push(sequence[3])
stack.push(sequence[4])
stack.push(sequence[5])
stack.pretty_print()

print "\n4) Create New Sequence By Popping From Stack"
new_sequence = list()
new_sequence.append(stack.pop())
new_sequence.append(stack.pop())
new_sequence.append(stack.pop())
new_sequence.append(stack.pop())
new_sequence.append(stack.pop())
new_sequence.append(stack.pop())

print "\n5) Print new sequence... notice anything?"
print "new_sequence = " + str(new_sequence)




1) Creating an empty stack of numbers...

2) Create an ordered sequence... 
sequence = [0, 1, 2, 3, 4, 5]

3) Push sequence onto my stack

--------TOP---------
5
--------------------
4
--------------------
3
--------------------
2
--------------------
1
--------------------
0
-----------------------
---------(table)-------
-----------------------
-- --             -- --
-- --             -- --
-- --             -- --
-- --             -- --
--                --
--                --



4) Create New Sequence By Popping From Stack

5) Print new sequence... notice anything?
new_sequence = [5, 4, 3, 2, 1, 0]


Testing the stack

In [12]:
import numpy as np

In [19]:
def r_tgg(t):
    r_t_out = np.zeros(stack_width) #How wide are the vectors v within the stack
    
    for i in xrange(0, t+1):  #This loop only goes till t
        #temp  = min(s[t][i], max(0 , 1 - sum(s[t][i+1:t+1])))
        temp = min(s[t][i],max(0,1 - sum(s[t][i+1:t+1])))
        r_t_out = r_t_out + (temp * V[t][i])
        
    return(r_t_out)


def r_t(t):
    r_t_out = np.zeros(stack_width)
    for i in xrange(0,t+1):
        temp = min(s[t][i],max(0,1 - sum(s[t][i+1:t+1])))
        r_t_out += temp * V[t][i]
    return r_t_out


def s_t(i, t , u, d):
    #i is position index
    #t is time index
    #u is "up", what is being popped out, indexed by t
    #d is "down", what is being pushed in, indexed by t
    
    
    if(i >= 0 and i <t):
        
        inner_sum = sum(s[t-1][i+1:t]) #t as upper limit excludes t 
        #effectively making it from i+1 to t-1
        #s is 2d as both time and positions at each time step
        
        out = max(0, s[t-1][i] - max(0 , u[t] - inner_sum ) )
        
        return(out)
        
    elif(i == t):
        return(d[t])
        
    else:
        print("Undefined i -> t relationship")
            

In [20]:
stack_width = 3
copy_length = 5

v_0 = np.zeros(stack_width)
v_0[0] = 1

v_1 = np.zeros(stack_width)
v_1[1] = 1

v_2 = np.zeros(stack_width)
v_2[2] = 1

V = list() #Overall stack over time
s = list() #Stack strengths
d = list() #Push strengths
u = list() #Pop strengths


def pushAndPop(v_t, d_t, u_t, t=len(V)):
    
    d.append(d_t)
    u.append(u_t)
    
    # For s
    new_s = np.zeros(t+1)
    
    for i in xrange(t+1):
        new_s = s_t(i, t, u, d)
        
    s.append(new_s)
    
    
    #For V
    
    if len(V) == 0:
        V_t = np.zeros((1, stack_width)) #2d matrix
        V_t = V_t + v_t #
        
    else:
        depth = len(V[-1])
        V_t = np.zeros( (depth+1, stack_width) )
        
        for i in xrange(depth):
            V_t[i] = V_t[i] + V[-1][i]
        V_t[depth] = V_t[depth] + v_t
        
        
    V.append(V_t)
    return(r_t(t))


#print(str(pushAndPop(v_0,0.8,0.0,0)))
print(str(pushAndPop(v_0,0.8,0.0,0)))







TypeError: 'float' object has no attribute '__getitem__'

In [21]:
import numpy as np

stack_width = 3
copy_length = 5

v_0 = np.zeros(stack_width)
v_0[0] = 1
v_1 = np.zeros(stack_width)
v_1[1] = 1
v_2 = np.zeros(stack_width)
v_2[2] = 1

# INIT
V = list() # stack states
s = list() # stack strengths 
d = list() # push strengths
u = list() # pop strengths

def r_t(t):
    r_t_out = np.zeros(stack_width)
    for i in xrange(0,t+1):
        temp = min(s[t][i],max(0,1 - sum(s[t][i+1:t+1])))
        r_t_out += temp * V[t][i]
    return r_t_out
    
def s_t(i,t,u,d):
    if(i >= 0 and i < t):
        inner_sum = s[t-1][i+1:t]
        return max(0,s[t-1][i] - max(0,u[t] - sum(inner_sum)))
    elif(i == t):
        return d[t]
    else:
        print "Undefined i -> t relationship"

def pushAndPop(v_t,d_t,u_t,t=len(V)):

  d.append(d_t)
  u.append(u_t)

  new_s = np.zeros(t+1)
  for i in xrange(t+1):
      new_s[i] = s_t(i,t,u,d)
  s.append(new_s)
  
  if(len(V) == 0):
      V_t = np.zeros((1,stack_width))
      V_t += v_t
  else:
      depth = len(V[-1])
      V_t = np.zeros((depth+1,stack_width))
      for i in xrange(depth):
        V_t[i] += V[-1][i]
      V_t[depth] += v_t
  
  V.append(V_t)
  return r_t(t)

print str(pushAndPop(v_0,0.8,0.0,0))

[ 0.8  0.   0. ]


In [22]:
whos

Variable      Type        Data/Info
-----------------------------------
V             list        n=1
copy_length   int         5
d             list        n=1
np            module      <module 'numpy' from '/ho<...>ages/numpy/__init__.pyc'>
pushAndPop    function    <function pushAndPop at 0x7f57483de140>
r_t           function    <function r_t at 0x7f57483dec08>
r_tgg         function    <function r_tgg at 0x7f57484167d0>
s             list        n=1
s_t           function    <function s_t at 0x7f57483de758>
stack_width   int         3
u             list        n=1
v_0           ndarray     3: 3 elems, type `float64`, 24 bytes
v_1           ndarray     3: 3 elems, type `float64`, 24 bytes
v_2           ndarray     3: 3 elems, type `float64`, 24 bytes


In [23]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [32]:
import numpy as np

stack_width = 3
copy_length = 5

v_0 = np.zeros(stack_width)
v_0[0] = 1

v_1 = np.zeros(stack_width)
v_1[1] = 1

v_2 = np.zeros(stack_width)
v_2[2] = 1

V = list() #Overall stack over time
s = list() #Stack strengths
d = list() #Push strengths
u = list() #Pop strengths



def r_t(t):
    r_t_out = np.zeros(stack_width) #How wide are the vectors v within the stack
    
    for i in xrange(0, t+1):  #This loop only goes till t
        #temp  = min(s[t][i], max(0 , 1 - sum(s[t][i+1:t+1])))
        temp = min(s[t][i],max(0,1 - sum(s[t][i+1:t+1])))
        r_t_out = r_t_out + (temp * V[t][i])
        
    return(r_t_out)


def s_t(i, t , u, d):
    #i is position index
    #t is time index
    #u is "up", what is being popped out, indexed by t
    #d is "down", what is being pushed in, indexed by t
    
    
    if(i >= 0 and i <t):
        
        inner_sum = sum(s[t-1][i+1:t]) #t as upper limit excludes t 
        #effectively making it from i+1 to t-1
        #s is 2d as both time and positions at each time step
        
        out = max(0, s[t-1][i] - max(0 , u[t] - inner_sum ) )
        
        return(out)
        
    elif(i == t):
        return(d[t])
        
    else:
        print("Undefined i -> t relationship")
            


def pushAndPop(v_t, d_t, u_t, t=len(V)):
    
    d.append(d_t)
    u.append(u_t)
    
    # For s
    new_s = np.zeros(t+1)
    
    for i in xrange(t+1):
        new_s[i] = s_t(i, t, u, d)
        
    s.append(new_s)
    
    
    #For V
    
    if len(V) == 0:
        V_t = np.zeros((1, stack_width)) #2d matrix
        V_t = V_t + v_t #
        
    else:
        depth = len(V[-1])
        V_t = np.zeros( (depth+1, stack_width) )
        
        for i in xrange(depth):
            V_t[i] = V_t[i] + V[-1][i]
        V_t[depth] = V_t[depth] + v_t
        
        
    V.append(V_t)
    print(V_t)
    print(t)
    return(r_t(t))


print(str(pushAndPop(v_0,0.8,0.0,0)))
print(str(pushAndPop(v_1,0.5,0.1,1)))
print(str(pushAndPop(v_2,0.9,0.9,2)))


# Stack is empty again
V = list() # stack states
s = list() # stack strengths 
d = list() # push strengths
u = list() # pop strengths


assert str(pushAndPop(v_0,0.8,0.0,0)) == str((0.8*v_0))
assert str(pushAndPop(v_1,0.5,0.1,1)) == str((0.5*v_0) + (0.5*v_1))
assert str(pushAndPop(v_2,0.9,0.9,2)) == str((0.9*v_2) + (0.0*v_1) + (0.1*v_0))

print("Final S")
for i in range(3):
    print(s_t, 2-i, 2, u, d)

[[ 1.  0.  0.]]
0
[ 0.8  0.   0. ]
[[ 1.  0.  0.]
 [ 0.  1.  0.]]
1
[ 0.5  0.5  0. ]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
2
[ 0.1  0.   0.9]
[[ 1.  0.  0.]]
0
[[ 1.  0.  0.]
 [ 0.  1.  0.]]
1
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
2
Final S
(<function s_t at 0x7f57483de140>, 2, 2, [0.0, 0.1, 0.9], [0.8, 0.5, 0.9])
(<function s_t at 0x7f57483de140>, 1, 2, [0.0, 0.1, 0.9], [0.8, 0.5, 0.9])
(<function s_t at 0x7f57483de140>, 0, 2, [0.0, 0.1, 0.9], [0.8, 0.5, 0.9])
