In [1]:
class VerySimpleStack:
    
    def __init__(self):
        self.contents = list()
        
    def push(self,item):
        self.contents.append(item)
    
    def pop(self):
        item = self.contents[-1]
        self.contents = self.contents[:-1]
        return item
    
    def pretty_print(self):
      i = 1
      print "\n--------TOP---------"
      for item in (self.contents):
          if(i != 1):
              print "--------------------"            
          print self.contents[-i]
          i+=1

      print  "-----------------------"
      print  "---------(table)-------"
      print  "-----------------------"
      print  "-- --             -- --"            
      print  "-- --             -- --"            
      print  "-- --             -- --"            
      print  "-- --             -- --"            
      print  "--                --"            
      print  "--                --\n\n"            
      
        

print "1) Creating an empty stack of books..."
stack = VerySimpleStack()

print "2) Pushing two books onto our stack..."
stack.push("Harry Potter and the Sorcerer's Stone")
stack.push("Harry Potter and the Chamber of Secrets")

print "3) Let's look at our stack..."
stack.pretty_print() # what order will this print?

print "4)Let's Pop a few...\n"
print "POP: " + stack.pop() # which one does this remove?
print "POP: " + stack.pop() # how bout this one?

print "\n5)Let's push a few more!"

stack.push("Harry Potter and the Prisoner of Azkaban")
stack.push("Harry Potter and the Goblet of Fire")
stack.push("Harry Potter and the Order of the Phoenix")
stack.push("Harry Potter and the Half-Blood Prince")
stack.push("Harry Potter and the Deathly Hallows")


print "\n6)Let's look at our stack again..."
stack.pretty_print()




1) Creating an empty stack of books...
2) Pushing two books onto our stack...
3) Let's look at our stack...

--------TOP---------
Harry Potter and the Chamber of Secrets
--------------------
Harry Potter and the Sorcerer's Stone
-----------------------
---------(table)-------
-----------------------
-- --             -- --
-- --             -- --
-- --             -- --
-- --             -- --
--                --
--                --


4)Let's Pop a few...

POP: Harry Potter and the Chamber of Secrets
POP: Harry Potter and the Sorcerer's Stone

5)Let's push a few more!

6)Let's look at our stack again...

--------TOP---------
Harry Potter and the Deathly Hallows
--------------------
Harry Potter and the Half-Blood Prince
--------------------
Harry Potter and the Order of the Phoenix
--------------------
Harry Potter and the Goblet of Fire
--------------------
Harry Potter and the Prisoner of Azkaban
-----------------------
---------(table)-------
-----------------------
-- --         

In [2]:
class VerySimpleStack:
    
    def __init__(self):
        self.contents = list()
        
    def push(self,item):
        self.contents.append(item)
    
    def pop(self):
        item = self.contents[-1]
        self.contents = self.contents[:-1]
        return item
    
    def pretty_print(self):
      i = 1
      print "\n--------TOP---------"
      for item in (self.contents):
          if(i != 1):
              print "--------------------"            
          print self.contents[-i]
          i+=1

      print  "-----------------------"
      print  "---------(table)-------"
      print  "-----------------------"
      print  "-- --             -- --"            
      print  "-- --             -- --"            
      print  "-- --             -- --"            
      print  "-- --             -- --"            
      print  "--                --"            
      print  "--                --\n\n"            
      
        

print "1) Creating an empty stack of numbers..."
stack = VerySimpleStack()

print "\n2) Create an ordered sequence... "
sequence = [0,1,2,3,4,5]
print "sequence = " + str(sequence)

print "\n3) Push sequence onto my stack"
stack.push(sequence[0])
stack.push(sequence[1])
stack.push(sequence[2])
stack.push(sequence[3])
stack.push(sequence[4])
stack.push(sequence[5])
stack.pretty_print()

print "\n4) Create New Sequence By Popping From Stack"
new_sequence = list()
new_sequence.append(stack.pop())
new_sequence.append(stack.pop())
new_sequence.append(stack.pop())
new_sequence.append(stack.pop())
new_sequence.append(stack.pop())
new_sequence.append(stack.pop())

print "\n5) Print new sequence... notice anything?"
print "new_sequence = " + str(new_sequence)




1) Creating an empty stack of numbers...

2) Create an ordered sequence... 
sequence = [0, 1, 2, 3, 4, 5]

3) Push sequence onto my stack

--------TOP---------
5
--------------------
4
--------------------
3
--------------------
2
--------------------
1
--------------------
0
-----------------------
---------(table)-------
-----------------------
-- --             -- --
-- --             -- --
-- --             -- --
-- --             -- --
--                --
--                --



4) Create New Sequence By Popping From Stack

5) Print new sequence... notice anything?
new_sequence = [5, 4, 3, 2, 1, 0]


Testing the stack

In [12]:
import numpy as np

In [19]:
def r_tgg(t):
    r_t_out = np.zeros(stack_width) #How wide are the vectors v within the stack
    
    for i in xrange(0, t+1):  #This loop only goes till t
        #temp  = min(s[t][i], max(0 , 1 - sum(s[t][i+1:t+1])))
        temp = min(s[t][i],max(0,1 - sum(s[t][i+1:t+1])))
        r_t_out = r_t_out + (temp * V[t][i])
        
    return(r_t_out)


def r_t(t):
    r_t_out = np.zeros(stack_width)
    for i in xrange(0,t+1):
        temp = min(s[t][i],max(0,1 - sum(s[t][i+1:t+1])))
        r_t_out += temp * V[t][i]
    return r_t_out


def s_t(i, t , u, d):
    #i is position index
    #t is time index
    #u is "up", what is being popped out, indexed by t
    #d is "down", what is being pushed in, indexed by t
    
    
    if(i >= 0 and i <t):
        
        inner_sum = sum(s[t-1][i+1:t]) #t as upper limit excludes t 
        #effectively making it from i+1 to t-1
        #s is 2d as both time and positions at each time step
        
        out = max(0, s[t-1][i] - max(0 , u[t] - inner_sum ) )
        
        return(out)
        
    elif(i == t):
        return(d[t])
        
    else:
        print("Undefined i -> t relationship")
            

In [20]:
stack_width = 3
copy_length = 5

v_0 = np.zeros(stack_width)
v_0[0] = 1

v_1 = np.zeros(stack_width)
v_1[1] = 1

v_2 = np.zeros(stack_width)
v_2[2] = 1

V = list() #Overall stack over time
s = list() #Stack strengths
d = list() #Push strengths
u = list() #Pop strengths


def pushAndPop(v_t, d_t, u_t, t=len(V)):
    
    d.append(d_t)
    u.append(u_t)
    
    # For s
    new_s = np.zeros(t+1)
    
    for i in xrange(t+1):
        new_s = s_t(i, t, u, d)
        
    s.append(new_s)
    
    
    #For V
    
    if len(V) == 0:
        V_t = np.zeros((1, stack_width)) #2d matrix
        V_t = V_t + v_t #
        
    else:
        depth = len(V[-1])
        V_t = np.zeros( (depth+1, stack_width) )
        
        for i in xrange(depth):
            V_t[i] = V_t[i] + V[-1][i]
        V_t[depth] = V_t[depth] + v_t
        
        
    V.append(V_t)
    return(r_t(t))


#print(str(pushAndPop(v_0,0.8,0.0,0)))
print(str(pushAndPop(v_0,0.8,0.0,0)))







TypeError: 'float' object has no attribute '__getitem__'

In [21]:
import numpy as np

stack_width = 3
copy_length = 5

v_0 = np.zeros(stack_width)
v_0[0] = 1
v_1 = np.zeros(stack_width)
v_1[1] = 1
v_2 = np.zeros(stack_width)
v_2[2] = 1

# INIT
V = list() # stack states
s = list() # stack strengths 
d = list() # push strengths
u = list() # pop strengths

def r_t(t):
    r_t_out = np.zeros(stack_width)
    for i in xrange(0,t+1):
        temp = min(s[t][i],max(0,1 - sum(s[t][i+1:t+1])))
        r_t_out += temp * V[t][i]
    return r_t_out
    
def s_t(i,t,u,d):
    if(i >= 0 and i < t):
        inner_sum = s[t-1][i+1:t]
        return max(0,s[t-1][i] - max(0,u[t] - sum(inner_sum)))
    elif(i == t):
        return d[t]
    else:
        print "Undefined i -> t relationship"

def pushAndPop(v_t,d_t,u_t,t=len(V)):

  d.append(d_t)
  u.append(u_t)

  new_s = np.zeros(t+1)
  for i in xrange(t+1):
      new_s[i] = s_t(i,t,u,d)
  s.append(new_s)
  
  if(len(V) == 0):
      V_t = np.zeros((1,stack_width))
      V_t += v_t
  else:
      depth = len(V[-1])
      V_t = np.zeros((depth+1,stack_width))
      for i in xrange(depth):
        V_t[i] += V[-1][i]
      V_t[depth] += v_t
  
  V.append(V_t)
  return r_t(t)

print str(pushAndPop(v_0,0.8,0.0,0))

[ 0.8  0.   0. ]


In [22]:
whos

Variable      Type        Data/Info
-----------------------------------
V             list        n=1
copy_length   int         5
d             list        n=1
np            module      <module 'numpy' from '/ho<...>ages/numpy/__init__.pyc'>
pushAndPop    function    <function pushAndPop at 0x7f57483de140>
r_t           function    <function r_t at 0x7f57483dec08>
r_tgg         function    <function r_tgg at 0x7f57484167d0>
s             list        n=1
s_t           function    <function s_t at 0x7f57483de758>
stack_width   int         3
u             list        n=1
v_0           ndarray     3: 3 elems, type `float64`, 24 bytes
v_1           ndarray     3: 3 elems, type `float64`, 24 bytes
v_2           ndarray     3: 3 elems, type `float64`, 24 bytes


In [23]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [1]:
import numpy as np

stack_width = 3
copy_length = 5

v_0 = np.zeros(stack_width)
v_0[0] = 1

v_1 = np.zeros(stack_width)
v_1[1] = 1

v_2 = np.zeros(stack_width)
v_2[2] = 1

V = list() #Overall stack over time
s = list() #Stack strengths
d = list() #Push strengths
u = list() #Pop strengths



def r_t(t):
    r_t_out = np.zeros(stack_width) #How wide are the vectors v within the stack
    
    for i in xrange(0, t+1):  #This loop only goes till t
        #temp  = min(s[t][i], max(0 , 1 - sum(s[t][i+1:t+1])))
        temp = min(s[t][i],max(0,1 - sum(s[t][i+1:t+1])))
        r_t_out = r_t_out + (temp * V[t][i])
        
    return(r_t_out)


def s_t(i, t , u, d):
    #i is position index
    #t is time index
    #u is "up", what is being popped out, indexed by t
    #d is "down", what is being pushed in, indexed by t
    
    
    if(i >= 0 and i <t):
        
        inner_sum = sum(s[t-1][i+1:t]) #t as upper limit excludes t 
        #effectively making it from i+1 to t-1
        #s is 2d as both time and positions at each time step
        
        out = max(0, s[t-1][i] - max(0 , u[t] - inner_sum ) )
        
        return(out)
        
    elif(i == t):
        return(d[t])
        
    else:
        print("Undefined i -> t relationship")
            


def pushAndPop(v_t, d_t, u_t, t=len(V)):
    
    d.append(d_t)
    u.append(u_t)
    
    # For s
    new_s = np.zeros(t+1)
    
    for i in xrange(t+1):
        new_s[i] = s_t(i, t, u, d)
        
    s.append(new_s)
    
    
    #For V
    
    if len(V) == 0:
        V_t = np.zeros((1, stack_width)) #2d matrix
        V_t = V_t + v_t #
        
    else:
        depth = len(V[-1])
        V_t = np.zeros( (depth+1, stack_width) )
        
        for i in xrange(depth):
            V_t[i] = V_t[i] + V[-1][i]
        V_t[depth] = V_t[depth] + v_t
        
        
    V.append(V_t)
    print(V_t)
    print(t)
    return(r_t(t))


print(str(pushAndPop(v_0,0.8,0.0,0)))
print(str(pushAndPop(v_1,0.5,0.1,1)))
print(str(pushAndPop(v_2,0.9,0.9,2)))


# Stack is empty again
V = list() # stack states
s = list() # stack strengths 
d = list() # push strengths
u = list() # pop strengths


assert str(pushAndPop(v_0,0.8,0.0,0)) == str((0.8*v_0))
assert str(pushAndPop(v_1,0.5,0.1,1)) == str((0.5*v_0) + (0.5*v_1))
assert str(pushAndPop(v_2,0.9,0.9,2)) == str((0.9*v_2) + (0.0*v_1) + (0.1*v_0))

print("Final S")
for i in range(3):
    print(s_t, 2-i, 2, u, d)

[[ 1.  0.  0.]]
0
[ 0.8  0.   0. ]
[[ 1.  0.  0.]
 [ 0.  1.  0.]]
1
[ 0.5  0.5  0. ]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
2
[ 0.1  0.   0.9]
[[ 1.  0.  0.]]
0
[[ 1.  0.  0.]
 [ 0.  1.  0.]]
1
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
2
Final S
(<function s_t at 0x7fd1e31369b0>, 2, 2, [0.0, 0.1, 0.9], [0.8, 0.5, 0.9])
(<function s_t at 0x7fd1e31369b0>, 1, 2, [0.0, 0.1, 0.9], [0.8, 0.5, 0.9])
(<function s_t at 0x7fd1e31369b0>, 0, 2, [0.0, 0.1, 0.9], [0.8, 0.5, 0.9])


In [3]:
def s_t_error(i, t, u, d, error):
    if(i >= 0 and i < t):
        if(s_t(i, t, u, d) >= 0):
            s_delta[t-1][i] = s_delta[t-1][i] + error
            if(max(0, u[t] - np.sum(s[t-1][i+1:t-0])) >= 0):
                u_delta[t] = u_delta[t] - error
                s_delta[t-1][i+1:t-0] = s_delta[t-1][i+1:t-0] + error
                
    elif(i == t):
        d_delta[t] = d_delta[t] + error
        
    else:
        print("Problem!")
        
        
        
def r_t_error(t, r_t_error ):
    
    for i in xrange(0, t+1):
        
        temp = min(s[t][i], max(0, 1-np.sum(s[t][i+1:t+1])))
        
        V_delta[t][i] = V_delta[t][i] + (temp * r_t_error)
        temp_error = np.sum(r_t_error * V[t][i])
        
        if(s[t][i] < max(0, 1 - np.sum(s[t][i+1:t+1]))):
            s_delta[t][i] = s_delta[t][i] + temp_error
            
        else:
            if(max(0, 1 - np.sum(s[t][i+1:t+1])) > 0):
                s_delta[t][i+1:t+1] = s_delta[t][i+1:t+1] - temp_error
                #  1 - -> 0 - when differentiated
        

In [27]:
import numpy as np

u_weights = np.array([0,0,0,0,0,0.01])
d_weights = np.array([1,1,1,0,0,0]).astype('float64')

stack_width = 2
copy_length = 5

sequence = np.array([
        [0.1, 0.2, 0.3],
        [0,   0,   0  ]            
                    ]).T

#Our seq is actually [0.1, 0.0] stacked over 
# [0.2, 0.0] over [0.3, 0.0]

V = list()
s = list()
d = list()
u = list()


V_delta = list()
s_delta = list()
d_delta = list()
u_delta = list()

In [28]:
def r_t(t):
  r_t_out = np.zeros(stack_width)
  for i in xrange(0,t+1):
    temp = min(s[t][i],max(0,1 - sum(s[t][i+1:t+1])))
    r_t_out += temp * V[t][i]
  return r_t_out
  
def r_t_error(t,r_t_error):
  for i in xrange(0, t+1):
    temp = min(s[t][i],max(0,1 - sum(s[t][i+1:t+1])))
    V_delta[t][i] += temp * r_t_error
    temp_error = sum(r_t_error * V[t][i])

    if(s[t][i] < max(0,1 - sum(s[t][i+1:t+1]))):
        s_delta[t][i] += temp_error
    else:
        if(max(0,1 - sum(s[t][i+1:t+1])) > 0):
          for j in xrange(t-i):
            s_delta[t][i+j+1] -= temp_error # minus equal becuase of the (1-).. and drop the 1


In [29]:
def s_t(i,t,u,d):
    if(i >= 0 and i < t):
        inner_sum = s[t-1][i+1:t]
        return max(0,s[t-1][i] - max(0,u[t] - sum(inner_sum)))
    elif(i == t):
        return d[t]
    else:
        print "Undefined i -> t relationship"
        
def s_t_error(i,t,u,d,error):
    if(i >= 0 and i < t):
        if(s_t(i,t,u,d) >= 0):
            s_delta[t-1][i] += error
            if(max(0,u[t] - sum(s[t-1][i+1:t])) >= 0):
                u_delta[t] -= error
                for j in xrange(t-(i+1)):
                  s_delta[t-1][i+j+1] += error
    elif(i == t):
        d_delta[t] += error
    else:
        print "Problem"

In [30]:
def pushAndPop(v_t, d_t, u_t, t = len(V), deriv=False, error = None):
    
    if(not deriv):
        
        d.append(d_t)
        d_delta.append(0)
        
        u.append(u_t)
        u_delta.append(0)
        
        new_s = np.zeros(t+1)
        
        for i in xrange(t+1):
            new_s[i] = s_t(i,t,u,d)
            
        s.append(new_s)
        s_delta.append(np.zeros(new_s.shape[0]))
        
        if(len(V) == 0):
            V_t = np.zeros((1,stack_width))
        else:
            depth = len(V[-1])
            V_t = np.zeros((depth+1, stack_width))
            for i in xrange(depth):
                V_t[i] = V_t[i] + V[-1][i]
            V_t[depth] = V_t[depth] + v_t

            
        V.append(V_t)
        
        nrow = V[-1].shape[0]
        ncol = V[-1].shape[1]
                 
        V_delta.append( np.zeros((nrow,ncol) ) )
        
        #V_delta.append(np.zeros_like(V[-1])) ##Changed
        
        return(r_t(t))
    
    else:
        
        r_t_error(t,error)
        for i in xrange(t+1):
            s_t_error((t+1) - (i+1), t, u, d, s_delta[t][i])
    

In [31]:
for i in xrange(500):
    alpha = 5 * ((1 - (float(i)/500))**2)
    sequence = np.array([
        [0.1, 0.2, 0.3],
        [0,   0,   0  ]            
                    ]).T
    
    
    V = list()
    s = list()
    d = list()
    u = list()

    V_delta = list()
    s_delta = list()
    d_delta = list()
    u_delta = list()
    
    
    out_0 = pushAndPop(sequence[0], d_weights[0], u_weights[0], t=0)
    out_1 = pushAndPop(sequence[1], d_weights[1], u_weights[1], t=1)
    out_2 = pushAndPop(sequence[2], d_weights[2], u_weights[2], t=2)
    
    y = np.array([1,0])
    
    out_3 = pushAndPop(sequence[2], d_weights[3], u_weights[3], t=3)
    out_4 = pushAndPop(sequence[2], d_weights[4], u_weights[4], t=4)
    out_5 = pushAndPop(sequence[2], d_weights[5], u_weights[5], t=5)
    
    pushAndPop(sequence[2], 0, u_weights[5], t=5, deriv=True, error=out_5 - (y*0.1))
    pushAndPop(sequence[2], 0, u_weights[4], t=4, deriv=True, error=out_4 - (y*0.2))
    pushAndPop(sequence[2], 0, u_weights[3], t=3, deriv=True, error=out_3 - (y*0.3))
    
    u_weights[3] = u_weights[3] - (alpha*u_delta[3])
    u_weights[4] = u_weights[4] - (alpha*u_delta[4])
    u_weights[5] = u_weights[5] - (alpha*u_delta[5])
    
    
    if(i%100 == 0):
        
        print("\n\nIteration:")
        print(i)
        print(out_3[0])
        print(out_4[0])
        print(out_5[0])



Iteration:
0
0.3
0.3
0.299


Iteration:
100
0.3
0.3
0.3


Iteration:
200
0.3
0.3
0.3


Iteration:
300
0.3
0.3
0.3


Iteration:
400
0.3
0.3
0.3


In [36]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [46]:


import numpy as np

u_weights = np.array([0,0,0,1,0.1,0.9])
d_weights = np.array([1,1,1,0,0,0]).astype('float64')

stack_width = 2
copy_length = 5

sequence = np.array([
        [0.1, 0.2, 0.3],
        [0,   0,   0  ]            
                    ]).T

#Our seq is actually [0.1, 0.0] stacked over 
# [0.2, 0.0] over [0.3, 0.0]

V = list()
s = list()
d = list()
u = list()


V_delta = list()
s_delta = list()
d_delta = list()
u_delta = list()


def r_t(t):
  r_t_out = np.zeros(stack_width)
  for i in xrange(0,t+1):
    temp = min(s[t][i],max(0,1 - sum(s[t][i+1:t+1])))
    r_t_out += temp * V[t][i]
  return r_t_out
  
def r_t_error(t,r_t_error):
  for i in xrange(0, t+1):
    temp = min(s[t][i],max(0,1 - sum(s[t][i+1:t+1])))
    V_delta[t][i] += temp * r_t_error
    temp_error = sum(r_t_error * V[t][i])

    if(s[t][i] < max(0,1 - sum(s[t][i+1:t+1]))):
        s_delta[t][i] += temp_error
    else:
        if(max(0,1 - sum(s[t][i+1:t+1])) > 0):
          for j in xrange(t-i):
            s_delta[t][i+j+1] -= temp_error # minus equal becuase of the (1-).. and drop the 1
    
def s_t(i,t,u,d):
    if(i >= 0 and i < t):
        inner_sum = s[t-1][i+1:t]
        return max(0,s[t-1][i] - max(0,u[t] - sum(inner_sum)))
    elif(i == t):
        return d[t]
    else:
        print "Undefined i -> t relationship"
        
def s_t_error(i,t,u,d,error):
    if(i >= 0 and i < t):
        if(s_t(i,t,u,d) >= 0):
            s_delta[t-1][i] += error
            if(max(0,u[t] - sum(s[t-1][i+1:t])) >= 0):
                u_delta[t] -= error
                for j in xrange(t-(i+1)):
                  s_delta[t-1][i+j+1] += error
    elif(i == t):
        d_delta[t] += error
    else:
        print "Problem"
        
        
def pushAndPop(v_t, d_t, u_t, t = len(V), deriv=False, error = None):
    
    if(not deriv):
        
        d.append(d_t)
        d_delta.append(0)
        
        u.append(u_t)
        u_delta.append(0)
        
        new_s = np.zeros(t+1)
        
        for i in xrange(t+1):
            new_s[i] = s_t(i,t,u,d)
            
        s.append(new_s)
        s_delta.append(np.zeros(new_s.shape[0]))
        
        if(len(V) == 0):
            V_t = np.zeros((1,stack_width))
        else:
            depth = len(V[-1])
            V_t = np.zeros((depth+1, stack_width))
            for i in xrange(depth):
                V_t[i] = V_t[i] + V[-1][i]
            V_t[depth] = V_t[depth] + v_t

            
        V.append(V_t)
        
        nrow = V[-1].shape[0]
        ncol = V[-1].shape[1]
                 
        V_delta.append( np.zeros((nrow,ncol) ) )
        
        #V_delta.append(np.zeros_like(V[-1])) ##Changed
        
        return(r_t(t))
    
    else:
        
        r_t_error(t,error)
        for i in xrange(t+1):
            s_t_error((t+1) - (i+1), t, u, d, s_delta[t][i])
                
for i in xrange(5000):
    alpha = 5 * ((1 - (float(i)/500))**2)
    sequence = np.array([
        [0.1, 0.2, 0.3],
        [0,   0,   0  ]            
                    ]).T
    
    
    V = list()
    s = list()
    d = list()
    u = list()

    V_delta = list()
    s_delta = list()
    d_delta = list()
    u_delta = list()
    
    
    out_0 = pushAndPop(sequence[0], d_weights[0], u_weights[0], t=0)
    out_1 = pushAndPop(sequence[1], d_weights[1], u_weights[1], t=1)
    out_2 = pushAndPop(sequence[2], d_weights[2], u_weights[2], t=2)
    
    y = np.array([1,0])
    
    out_3 = pushAndPop(sequence[2], d_weights[3], u_weights[3], t=3)
    out_4 = pushAndPop(sequence[2], d_weights[4], u_weights[4], t=4)
    out_5 = pushAndPop(sequence[2], d_weights[5], u_weights[5], t=5)
    
    pushAndPop(sequence[2], 0, u_weights[5], t=5, deriv=True, error=out_5 - (y*0.1))
    pushAndPop(sequence[2], 0, u_weights[4], t=4, deriv=True, error=out_4 - (y*0.2))
    pushAndPop(sequence[2], 0, u_weights[3], t=3, deriv=True, error=out_3 - (y*0.3))
    
    u_weights[3] = u_weights[3] - (alpha*u_delta[3])
    u_weights[4] = u_weights[4] - (alpha*u_delta[4])
    u_weights[5] = u_weights[5] - (alpha*u_delta[5])
    
    
    if(i%100 == 0):
        
        print("\n\nIteration:")
        print(i)
        print(out_3[0])
        print(out_4[0])
        print(out_5[0])



Iteration:
0
0.2
0.18
0.0


Iteration:
100
0.3
0.3
0.199503361298


Iteration:
200
0.3
0.289852490568
0.195937739188


Iteration:
300
0.3
0.228993527275
0.116529984438


Iteration:
400
0.291441418005
0.214066958465
0.0991205550322


Iteration:
500
0.29108474242
0.213291202411
0.0991796650796


Iteration:
600
0.290793595803
0.212587897356
0.0992328420551


Iteration:
700
0.289897883504
0.208734371384
0.0995152501517


Iteration:
800
0.252179055698
0.118536939973
0.0


Iteration:
900
0.3
0.3
0.197606768856


Iteration:
1000
0.3
0.3
0.206132660692


Iteration:
1100
0.3
0.3
0.166660371433


Iteration:
1200
0.3
0.182819607104
0.0


Iteration:
1300
0.3
0.3
0.258375134815


Iteration:
1400
0.3
0.3
0.3


Iteration:
1500
0.3
0.3
0.3


Iteration:
1600
0.3
0.3
0.3


Iteration:
1700
0.3
0.3
0.3


Iteration:
1800
0.3
0.3
0.3


Iteration:
1900
0.3
0.3
0.3


Iteration:
2000
0.3
0.3
0.3


Iteration:
2100
0.3
0.3
0.3


Iteration:
2200
0.3
0.3
0.3


Iteration:
2300
0.3
0.3
0.3


Iteration:
2400
0.3
0.